#!/usr/bin/env python3
"""Apply checked local prose layouts while preserving source text and controls."""
from __future__ import annotations
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'tools'))
from srwz.chinese_prose import logical_prose_text
from srwz.text import CONTROL_NOTATION,normalize_original_fullwidth_ascii

def digest(data):
    return hashlib.sha256(data).hexdigest()

def apply(preview_path: Path,receipt_path: Path,snapshot_root: Path):
    preview_bytes=preview_path.read_bytes();preview=json.loads(preview_bytes)
    for name,expected in preview['inputs'].items():
        if ':' not in name and digest((ROOT/name).read_bytes())!=expected:
            raise ValueError(f'Preview source drift: {name}')
    selected={}
    for row in preview['records']:
        key=row['path'],row['id']
        if key not in selected or row['variant']=='balanced_compact':selected[key]=row
    if len(selected)!=1398 or any(row.get('error') for row in selected.values()):
        raise ValueError('Incomplete or blocked prose preview')
    documents={};originals={};changes=[];counts=Counter()
    for (name,identity),row in selected.items():
        if name not in documents:
            originals[name]=(ROOT/name).read_bytes();documents[name]=json.loads(originals[name])
        target=next(x for x in documents[name]['entries'] if x['id']==identity)
        before=target['translation'];after=row['after']
        clean=lambda t:CONTROL_NOTATION.sub('',normalize_original_fullwidth_ascii(t))
        equal=(clean(before).replace('\n','')==clean(after).replace('\n','')) if row['surface'].startswith('library_') else logical_prose_text(clean(before))==logical_prose_text(clean(after))
        if not equal or not row.get('content_exact'):
            raise ValueError(f'Visible text changed: {identity}')
        tokens=CONTROL_NOTATION.findall(before)
        if tokens and CONTROL_NOTATION.findall(after)!=tokens:
            raise ValueError(f'Existing controls changed: {identity}')
        if max(row['line_widths_px'])>row['maximum_width_cells']*row['default_advance_px']:
            raise ValueError(f'Pixel overflow: {identity}')
        if row.get('source_rows_upper_bound') is not None and row['lines']>row['source_rows_upper_bound']:
            raise ValueError(f'Row overflow: {identity}')
        if after!=before:
            target['translation']=after;counts[row['surface']]+=1
            changes.append(dict(path=name,id=identity,surface=row['surface'],
                before_sha256=digest(before.encode()),after_sha256=digest(after.encode())))
    documents['corpus/zh/menu/stage-overviews.json']['policy']['maximum_line_width']=30
    # Prepare and verify the entire plan before the first corpus mutation.
    outputs={name:(json.dumps(document,ensure_ascii=False,indent=2)+'\n').encode() for name,document in documents.items()}
    refs={}
    for name,data in originals.items():
        snapshot=snapshot_root/name;snapshot.parent.mkdir(parents=True,exist_ok=True)
        if snapshot.exists() and snapshot.read_bytes()!=data:raise ValueError(f'Snapshot collision: {name}')
        snapshot.write_bytes(data)
        refs[name]=dict(before_sha256=digest(data),after_sha256=digest(outputs[name]),snapshot=str(snapshot.relative_to(ROOT)))
    for name,data in outputs.items():(ROOT/name).write_bytes(data)
    receipt=dict(schema_version=1,batch_id='prose-width-optimization-20260928',applied=True,
        publication='local_only',iso_built=False,scanned=len(selected),changed=len(changes),
        counts=dict(counts),preview=dict(path=str(preview_path.relative_to(ROOT)),sha256=digest(preview_bytes)),
        sources=refs,changes=changes,controls='Existing controls and variables unchanged; only closed width scopes generated by the selected preview may be added to plain text.',
        verification='Every visible logical text, pixel width, source row budget and unchanged-source precondition checked before writeback.')
    receipt_path.parent.mkdir(parents=True,exist_ok=True);receipt_path.write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
    return dict(scanned=len(selected),changed=len(changes),counts=dict(counts))

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--preview',type=Path,required=True);p.add_argument('--receipt',type=Path,required=True);p.add_argument('--snapshot-root',type=Path,required=True)
    a=p.parse_args();print(json.dumps(apply(a.preview.resolve(),a.receipt.resolve(),a.snapshot_root.resolve()),ensure_ascii=False))
